-- ==============================================================================
-- MAGOS PLATFORM - Riddles Seed (fonte: crawsome/riddles, curado)
-- Removidos: fragmentos "My first is in...", riddles truncados, duplicatas por resposta
-- Corrigidos: erros tipográficos em perguntas
-- Total: 286 riddles | Categorias: natureza, animais, objetos, alimentos, abstrato
-- authorId: usr_001 (Mago Supremo / admin)
-- ==============================================================================

INSERT IGNORE INTO riddles (id, authorId, question, answer, hint, category, difficulty, points, solvedCount, views, isMonthly, isActive, qrCode, tags, monthlyPrize) VALUES
('rdl_001','usr_001','Almost everyone needs it, asks for it, gives it. But almost nobody takes it.','advice',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_002','usr_001','What goes up but never comes down?','age',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_003','usr_001','Die without me, never thank me. Walk right through me, never feel me.','air',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_004','usr_001','Today he is there to trip you up. And he will torture you tomorrow.','alcohol',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_005','usr_001','What do you throw out to use and take in when you''re done?','anchor',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_006','usr_001','I''m very tempting, so its said, I have a shiny coat of red.','apple',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_007','usr_001','I have many feathers to help me fly. I have a body and head.','arrow',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_008','usr_001','I can be moved. I can be rolled. But nothing will I hold.','ball',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_009','usr_001','A time when they''re green. A time when they''re brown.','bananas',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_010','usr_001','I sleep by day, I fly by night. I have no feathers to aid my flight.','bat',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_011','usr_001','I am the yellow hem of the sea''s blue skirt.','beach',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_012','usr_001','In the night a mountain, in the morning a meadow.','bed',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_013','usr_001','A warrior amongst the flowers, he bears a thrusting sword.','bee',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_014','usr_001','Thousands lay up gold within this house.','beehive',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_015','usr_001','Round as a button, deep as a well.','bell',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_016','usr_001','I am a fire''s best friend. When fat, my body fills with wind.','bellows',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_017','usr_001','You get many of me, but never enough.','birthday',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_018','usr_001','I am seen in the water. If seen in the sky, I am in the rainbow.','blue',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_019','usr_001','My life is often a volume of grief, your help is needed.','book',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_020','usr_001','Turns us on our backs, and open up our stomachs.','books',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_021','usr_001','I heard of a wonder, of words moth-eaten.','bookworm',NULL,'animais',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_022','usr_001','Two brothers we are, great burdens we bear.','boots',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_023','usr_001','I have a neck but no head. I have a body but no arm.','bottle',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_024','usr_001','As light as a feather, but you can''t hold it for ten minutes.','breath',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_025','usr_001','To cross the water I''m the way, for water I''m above.','bridge',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_026','usr_001','I have a hundred legs, but cannot stand.','broom',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_027','usr_001','A muttered rumble was heard from the pen.','bull',NULL,'animais',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_028','usr_001','What lies in a tunnel of darkness. That can only attack when pulled back?','bullet',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_029','usr_001','Flat as a leaf, round as a ring. Has two eyes, can''t see a thing.','button',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_030','usr_001','I have one eye. See near and far. I hold the moments you treasure.','camera',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_031','usr_001','My life can be measured in hours. I serve by being devoured.','candle',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_032','usr_001','What has 13 hearts but none beat?','cards',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_033','usr_001','What kind of pet always stays on the floor?','carpet',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_034','usr_001','Halo of water, tongue of wood. Skin of stone, long I''ve stood.','castle',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_035','usr_001','Stealthy as a shadow in the dead of night, cunning but affectionate.','cat',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_036','usr_001','I''m not really more than holes tied to more holes.','chain',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_037','usr_001','I have legs but walk not, a strong back but work not.','chair',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_038','usr_001','What''s black when you get it, red when you use it?','charcoal',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_039','usr_001','Not born, but from a Mother''s body drawn.','cheese',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_040','usr_001','I wear a red robe, with staff in hand, and a stone in my throat.','cherry',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_041','usr_001','A slow, solemn square-dance of warriors feinting.','chess',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_042','usr_001','What is it that given one, you''ll have either two or none?','choice',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_043','usr_001','This thing runs but cannot walk, sometimes sings but never talks.','clock',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_044','usr_001','I fly, yet I have no wings. I cry, yet I have no eyes.','cloud',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_045','usr_001','What''s black in the morning, red in the afternoon?','coal',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_046','usr_001','A little pool with two layers of wall around it.','coconut',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_047','usr_001','The man who made it didn''t need it.','coffin',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_048','usr_001','I am two-faced but bear only one. I have no legs but travel widely.','coin',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_049','usr_001','What can you catch but not throw?','cold',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_050','usr_001','Metal or bone I may be, many teeth I have.','comb',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_051','usr_001','I am so simple that I can only point.','compass',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_052','usr_001','You throw away the outside and cook the inside.','corn',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_053','usr_001','Whoever makes it, tells it not.','counterfeit',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_054','usr_001','The more of it there is, the less you see.','darkness',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_055','usr_001','Five hundred begins it, five hundred ends it.','david',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_056','usr_001','Some try to hide, some try to cheat.','death',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_057','usr_001','What is put on a table, cut, but never eaten?','deck',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_058','usr_001','I dig out tiny caves and store gold and silver in them.','dentist',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_059','usr_001','You will find me with four legs, but no hair.','desk',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_060','usr_001','A tiny bead, like fragile glass, strung along a cord of grass.','dew',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_061','usr_001','What has six faces and twenty-one eyes?','die',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_062','usr_001','What wears a coat in the winter and pants in the summer?','dog',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_063','usr_001','Hands she has but does not hold. Teeth she has but does not bite.','doll',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_064','usr_001','What kind of nut is empty at the center and has no shell?','doughnut',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_065','usr_001','A word I know, six letters it contains.','dozens',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_066','usr_001','This is in a realm of true and in a realm false.','dream',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_067','usr_001','Although my cow is dead, I still beat her. What a racket she makes.','drum',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_068','usr_001','People are hired to get rid of me.','dust',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_069','usr_001','I am the third from a sparkle bright, I thrive throughout.','earth',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_070','usr_001','You heard me before, yet you hear me again, then I die.','echo',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_071','usr_001','What has to be broken before it can be used?','egg',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_072','usr_001','I drift forever with the current down these long canals.','electricity',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_073','usr_001','Face with a tree, skin like the sea. A great beast I am.','elephant',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_074','usr_001','What word starts with ''E'', ends with ''E'', but only has one letter?','envelope',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_075','usr_001','What is pronounced like one letter, written with three letters.','eye',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_076','usr_001','Two horses, swiftest traveling, harnessed in a pair.','eyes',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_077','usr_001','When set loose I fly away. Never so cursed as when I go astray.','fart',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_078','usr_001','It''s in your hand though you can not feel it.','fate',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_079','usr_001','I make you weak at the worst of all times.','fear',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_080','usr_001','I am the outstretched fingers that seize and hold the wind.','feather',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_081','usr_001','I know a word of letters three. Add two, and fewer there will be!','few',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_082','usr_001','Long and thin, red within, with a nail at the end.','finger',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_083','usr_001','Feed me and I live, give me drink and I die.','fire',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_084','usr_001','Screaming, soaring seeking sky. Flowers of fire flying high.','firework',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_085','usr_001','Alive without breath, as cold as death, clad in mail never clinking.','fish',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_086','usr_001','I march before armies, a thousand salute me.','flag',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_087','usr_001','When they are caught, they are thrown away.','fleas',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_088','usr_001','A thousand colored folds stretch toward the sky.','flower',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_089','usr_001','Who spends the day at the window, goes to the table for meals.','fly',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_090','usr_001','My second is performed by my first, and it is thought a thief.','footstep',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_091','usr_001','I bubble and laugh and spit water in your face.','fountain',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_092','usr_001','I have four legs but no tail. Usually I am heard only at night.','frog',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_093','usr_001','Goes over all the hills and hollows. Bites hard, but never swallows.','frost',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_094','usr_001','Born of earth, but with none of its strength.','glass',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_095','usr_001','Without a bridle, or a saddle, across a thing I ride a-straddle.','glasses',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_096','usr_001','What do you fill with empty hands?','gloves',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_097','usr_001','I drive men mad for love of me. Easily beaten, never free.','gold',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_098','usr_001','The sun bakes them, the hand breaks them, the foot treads on them.','grapes',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_099','usr_001','The sharp slim blade, that cuts the wind.','grass',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_100','usr_001','So cold, damp and dark this place.','grave',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_101','usr_001','They can be harbored, but few hold water.','grudge',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_102','usr_001','Long and slinky like a trout, never sings till its guts come out.','gun',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_103','usr_001','I have one, you have one.','habit',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_104','usr_001','What is that over the head and under the hat?','hair',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_105','usr_001','Two in a whole and four in a pair.','half',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_106','usr_001','How far will a blind dog walk into a forest?','halfway',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_107','usr_001','They are many and one, they wave and they drum.','hands',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_108','usr_001','Inside a burning house, this thing is best to make.','haste',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_109','usr_001','You can tumble in it, roll in it, burn it, animals eat it.','hay',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_110','usr_001','I''m the source of all emotion, but I''m caged in a white prison.','heart',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_111','usr_001','What gets bigger the more you take away from it?','hole',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_112','usr_001','When you stop and look, you can always see me.','horizon',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_113','usr_001','What always goes to bed with his shoes on?','horse',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_114','usr_001','Two bodies have I, though both joined in one.','hourglass',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_115','usr_001','Power enough to smash ships and crush roofs.','ice',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_116','usr_001','Lighter than what I am made of, more of me is hidden.','iceberg',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_117','usr_001','Glittering points that downward thrust.','icicle',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_118','usr_001','What word has kst in the middle, in the beginning, and at the end?','inkstand',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_119','usr_001','Ripped from my mother''s womb. Beaten and burned, I become.','iron',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_120','usr_001','I can be cracked, I can be made.','joke',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_121','usr_001','I cut through evil like a double edged sword.','justice',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_122','usr_001','What force and strength cannot get through.','key',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_123','usr_001','What goes through a door but never goes in.','keyhole',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_124','usr_001','Of no use to one, bliss to two.','kiss',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_125','usr_001','I love to dance and twist and prance.','kite',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_126','usr_001','Iron roof, glass walls, burns and burns and never falls.','lantern',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_127','usr_001','I am the red tongue of the earth, that buries cities.','lava',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_128','usr_001','Walk on the living, they don''t even mumble.','leaves',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_129','usr_001','I do not breathe, but I run and jump.','leg',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_130','usr_001','What building has the most stories?','library',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_131','usr_001','I''m sometimes white and always wrong.','lie',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_132','usr_001','What can fill a room but takes up no space?','light',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_133','usr_001','What goes in the water black and comes out red?','lobster',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_134','usr_001','A dagger thrust at my own heart, dictates the way I''m swayed.','lock',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_135','usr_001','In your fire you hear me scream, creaking and whining.','log',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_136','usr_001','What can touch someone once and last them a life time?','love',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_137','usr_001','I have rivers without water.','map',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_138','usr_001','Tool of thief, toy of queen.','mask',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_139','usr_001','Take one out and scratch my head, I am now black but once was red.','match',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_140','usr_001','What can bring back the dead. Make us cry, make us laugh?','memory',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_141','usr_001','I''m a god. I''m a planet. I measure heat.','mercury',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_142','usr_001','Something wholly unreal, yet seems real to I.','mind',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_143','usr_001','I look at you, you look at me, I raise my right.','mirror',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_144','usr_001','A hill full, a hole full, yet you cannot catch a bowl full.','mist',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_145','usr_001','What goes further the slower it goes?','money',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_146','usr_001','Always old, sometimes new. Never sad, sometimes blue.','moon',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_147','usr_001','What has roots as nobody sees, is taller than trees.','mountain',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_148','usr_001','What kind of room has no windows or doors?','mushroom',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_149','usr_001','At the sound of me, one may dream or stamp their feet.','music',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_150','usr_001','Who works when he plays and plays when he works?','musician',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_151','usr_001','I hide but my head is outside.','nail',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_152','usr_001','What is it that was given to you, belongs only to you.','name',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_153','usr_001','An iron horse with a flaxen tail.','needle',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_154','usr_001','A house of wood in a hidden place.','nest',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_155','usr_001','Hold the tail, while I fish for you.','net',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_156','usr_001','I can be written, I can be spoken, I can be exposed.','news',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_157','usr_001','Sometimes I am loud. And viewed with distaste.','noise',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_158','usr_001','What word is the same written forward, backward?','noon',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_159','usr_001','Gets rid of bad ones, short and tall.','noose',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_160','usr_001','I can run but not walk. Wherever I go, thought follows.','nose',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_161','usr_001','What does man love more than life, fear more than death?','nothing',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_162','usr_001','A little house full of meat, no door to go in and eat.','nut',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_163','usr_001','I am the fountain from which no one can drink.','oil',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_164','usr_001','Take off my skin, I won''t cry, but you will.','onion',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_165','usr_001','Gold in a leather bag, swinging on a tree.','orange',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_166','usr_001','What asks but never answers?','owl',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_167','usr_001','It holds most knowledge that has ever been said.','paper',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_168','usr_001','Half-way up the hill, I see you at last.','past',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_169','usr_001','The eight of us move forth and back.','pawns',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_170','usr_001','A seed am I, three letters make my name.','pea',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_171','usr_001','The strangest creature you''ll ever find.','peacock',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_172','usr_001','A house with two occupants, sometimes one.','peanut',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_173','usr_001','Lovely and round, I shine with pale light.','pearl',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_174','usr_001','I am the tool, for inspiring many.','pen',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_175','usr_001','I usually wear a yellow coat.','pencil',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_176','usr_001','What has a head, a tail, is brown, and has no legs?','penny',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_177','usr_001','A woman shoots her husband, then holds him under water.','photo',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_178','usr_001','I am a box that holds keys without locks.','piano',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_179','usr_001','What loses its head in the morning?','pillow',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_180','usr_001','What makes a loud noise when changing its jacket?','popcorn',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_181','usr_001','A skin have I, more eyes than one.','potato',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_182','usr_001','What can be swallowed, but can also swallow you?','pride',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_183','usr_001','He has married many women but has never married.','priest',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_184','usr_001','Three little letters. A paradox to some.','pun',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_185','usr_001','Different lights do make me strange, thus into different sizes.','pupil',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_186','usr_001','Only two backbones and thousands of ribs.','railroad',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_187','usr_001','I have split the one into five.','rainbow',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_188','usr_001','Break it and it is better, immediately set and harder.','record',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_189','usr_001','You can see nothing else, when you look in my face.','reflection',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_190','usr_001','What can be heard and caught but never seen?','remark',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_191','usr_001','To unravel me you need a simple key.','riddle',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_192','usr_001','It has no top or bottom, but it can hold flesh, bones.','ring',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_193','usr_001','What always runs but never walks, often murmurs?','river',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_194','usr_001','I run through hills. I veer around mountains.','road',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_195','usr_001','Ten men''s strength, ten men''s length.','rope',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_196','usr_001','What can burn the eyes, sting the mouth?','salt',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_197','usr_001','I build up castles. I tear down mountains.','sand',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_198','usr_001','I bind it and it walks. I loose it and it stops.','sandal',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_199','usr_001','My teeth are sharp, my back is straight.','saw',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_200','usr_001','I open wide and tight I shut, sharp am I.','scissors',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_201','usr_001','If you have it, you want to share it.','secret',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_202','usr_001','Tall in the morning, short at noon, gone at night.','shadow',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_203','usr_001','Of these things - I have two.','sharing',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_204','usr_001','Weight in my belly, trees on my back.','ship',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_205','usr_001','What has a neck and no head, two arms but no hands?','shirt',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_206','usr_001','Runs over fields and woods all day.','shoe',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_207','usr_001','In buckles or lace, they help set the pace.','shoes',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_208','usr_001','What five-letter word becomes shorter when you add two more letters?','short',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_209','usr_001','What is round as a dishpan, deep as a tub?','sieve',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_210','usr_001','What is so fragile that saying its name breaks it?','silence',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_211','usr_001','A beggar''s brother went out to sea and drowned.','sister',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_212','usr_001','Double my number, I''m less than a score.','six',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_213','usr_001','I am whole but incomplete. I have no eyes, yet I see.','skeleton',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_214','usr_001','When liquid splashes me, none seeps through.','skin',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_215','usr_001','I weaken all men for hours each day.','sleep',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_216','usr_001','A mile from end to end, yet as close to as a friend.','smile',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_217','usr_001','A house full, a yard full, a chimney full.','smoke',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_218','usr_001','If a man carried my burden, he would break his back.','snail',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_219','usr_001','I can sizzle like bacon, I am made with an egg.','snake',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_220','usr_001','White bird, featherless, flying out of paradise.','snow',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_221','usr_001','I saw a man in white, he looked quite a sight.','snowman',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_222','usr_001','You use it between your head and your toes.','soap',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_223','usr_001','I cannot be felt, seen or touched.','soul',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_224','usr_001','What surrounds the world, yet dwells within a thimble?','space',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_225','usr_001','A horrid monster hides from the day, with many legs.','spider',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_226','usr_001','I went to the woods and got it.','splinter',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_227','usr_001','I''m full of holes, yet I''m full of water.','sponge',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_228','usr_001','We travel much, yet prisoners are.','spurs',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_229','usr_001','A nut cracker up in a tree.','squirrel',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_230','usr_001','As a whole, I am both safe and secure.','stable',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_231','usr_001','What has wings, but cannot fly.','stage',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_232','usr_001','Upon me you can tread, though softly under cover.','stairs',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_233','usr_001','What goes around the world and stays in a corner?','stamp',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_234','usr_001','With pointed fangs it sits in wait.','stapler',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_235','usr_001','At night I come without being fetched.','stars',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_236','usr_001','The more you take, the more you leave behind.','steps',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_237','usr_001','Four of us are in your field.','suits',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_238','usr_001','What goes through the door without pinching itself?','sun',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_239','usr_001','I appear in the morning. But am always there.','sunlight',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_240','usr_001','Sleeping during the day, I hide away.','sunrise',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_241','usr_001','A dragon''s tooth in a mortal''s hand.','sword',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_242','usr_001','He has one and a person has two.','syllable',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_243','usr_001','Late afternoons I often bathe.','teabag',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_244','usr_001','What starts with a T, ends with a T, and has T in it?','teapot',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_245','usr_001','Thirty white horses on a red hill.','teeth',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_246','usr_001','You must keep this thing.','temper',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_247','usr_001','What is often returned, but never borrowed?','thanks',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_248','usr_001','What can''t you see, hear or feel, until its too late?','thief',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_249','usr_001','An open ended barrel, it is shaped like a hive.','thimble',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_250','usr_001','I walked and walked and at last I got it.','thorn',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_251','usr_001','Used left or right, I get to travel over cobblestone.','thumb',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_252','usr_001','Fatherless and motherless. Born without sin.','thunder',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_253','usr_001','When the day after tomorrow is yesterday.','thursday',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_254','usr_001','In we go, out we go. All around and in a row.','tides',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_255','usr_001','There are two meanings to me.','tie',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_256','usr_001','This thing all things devours.','time',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_257','usr_001','I never was, am always to be.','tomorrow',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_258','usr_001','Forward I''m heavy, but backwards I''m not.','ton',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_259','usr_001','Often held but never touched.','tongue',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_260','usr_001','Blend a teapot shot so the pearlies won''t rot!','toothpaste',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_261','usr_001','What gets wetter as it dries?','towel',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_262','usr_001','Reaching stiffly for the sky, I bare my fingers.','tree',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_263','usr_001','Creatures of power, creatures of grade.','trees',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_264','usr_001','Who is it that rows quickly with four oars?','turtle',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_265','usr_001','What goes up when the rain comes down?','umbrella',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_266','usr_001','My voice is tender, my waist is slender.','violin',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_267','usr_001','What instrument can make any sound and be heard?','voice',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_268','usr_001','My thunder comes before the lightning.','volcano',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_269','usr_001','We are five little objects of an everyday sort.','vowels',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_270','usr_001','I run around the city, but I never move.','wall',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_271','usr_001','As soft as silk, as white as milk, as bitter as gall.','walnut',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_272','usr_001','A harvest sown and reaped on the same day.','war',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_273','usr_001','Three lives have I.','water',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_274','usr_001','Bright as diamonds, loud as thunder.','waterfall',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_275','usr_001','The moon is my father. The sea is my mother.','wave',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_276','usr_001','As round as an apple. As deep as a cup.','well',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_277','usr_001','I go around in circles, but always straight ahead.','wheel',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_278','usr_001','A leathery snake, with a stinging bite.','whip',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_279','usr_001','Voiceless it cries, wingless it flutters.','wind',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_280','usr_001','I have four wings but cannot fly.','windmill',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_281','usr_001','There is an ancient invention.','window',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_282','usr_001','When young, I am sweet in the sun.','wine',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_283','usr_001','I am the heart that does not beat.','wood',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_284','usr_001','What is it that you must give before you can keep it?','word',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_285','usr_001','What does no man want, yet no man want to lose?','work',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_286','usr_001','What must be in the oven yet cannot be baked?','yeast',NULL,'alimentos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL);
