-- ==============================================================================
-- MAGOS PLATFORM - Extra Riddles Seed
-- 200 English riddles  : rdl_287  – rdl_486
-- 200 Portuguese riddles: rdl_pt_287 – rdl_pt_486
-- ==============================================================================

-- ── ENGLISH ──────────────────────────────────────────────────────────────────
INSERT IGNORE INTO riddles (id, authorId, question, answer, hint, category, difficulty, points, solvedCount, views, isMonthly, isActive, qrCode, tags, monthlyPrize) VALUES
('rdl_287','usr_001','I am small and hard, yet I hold a forest inside me.','acorn',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_288','usr_001','I am the first thing you learn, yet I never speak a word.','alphabet',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_289','usr_001','I carry more than my weight and never complain.','ant',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_290','usr_001','I paint the trees in fire and gold, then strip them bare.','autumn',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_291','usr_001','I swing to divide what stands tall.','axe',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_292','usr_001','I know nothing yet I am adored by all.','baby',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_293','usr_001','Fill me with breath and I rise. Pop me and I vanish.','balloon',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_294','usr_001','Animals sleep within my walls but I am not a house.','barn',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_295','usr_001','I hold things but have holes in my sides.','basket',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_296','usr_001','I grow on a man''s face but I am no plant.','beard',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_297','usr_001','Two wheels, no engine, yet it carries you far.','bicycle',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_298','usr_001','I keep you warm but I cannot feel the cold.','blanket',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_299','usr_001','I flow in rivers within you yet never wet the ground unless wounded.','blood',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_300','usr_001','Hard when alive, it outlasts the flesh that once covered it.','bone',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_301','usr_001','I am the master of your body yet I never give an order out loud.','brain',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_302','usr_001','I am born of grain, shaped by hands, and killed by hunger.','bread',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_303','usr_001','I began as something ugly and became beautiful without trying.','butterfly',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_304','usr_001','I hold what flies but have no wings myself.','cage',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_305','usr_001','I am a room with no door, a home with no roof.','cave',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_306','usr_001','I write in white and vanish when it rains.','chalk',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_307','usr_001','I have no beginning and no end, yet I am not forever.','circle',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_308','usr_001','Millions live in me yet I have no heartbeat of my own.','city',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_309','usr_001','I am a trap built by the smallest of hunters.','cobweb',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_310','usr_001','I travel billions of miles to briefly brighten your sky.','comet',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_311','usr_001','Every room has me but I hold nothing and cost nothing.','corner',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_312','usr_001','I am not a muscle yet I let you lift what fear cannot.','courage',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_313','usr_001','I sit above all yet touch no sky.','crown',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_314','usr_001','I divide the room from the world but I am paper-thin.','curtain',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_315','usr_001','I am born at midnight and die the same way.','day',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_316','usr_001','I was spent before I was earned and must be returned with more.','debt',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_317','usr_001','The more it has, the thirstier you become.','desert',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_318','usr_001','Pressure made me and nothing can break me.','diamond',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_319','usr_001','I hold your secrets but I cannot speak.','diary',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_320','usr_001','The more you look inside me, the less you know.','dictionary',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_321','usr_001','I stand between two worlds and open both ways.','door',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_322','usr_001','I kill without a weapon and leave without a trace except silence.','drought',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_323','usr_001','I take in everything yet hold nothing.','ear',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_324','usr_001','I hide the sun without touching it.','eclipse',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_325','usr_001','I look like a snake, live in water, and shock those who touch me.','eel',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_326','usr_001','I follow the day and lead the night.','evening',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_327','usr_001','I test without asking if you are ready.','exam',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_328','usr_001','I stand to divide yet I bring neighbors together.','fence',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_329','usr_001','I am left behind by those who move forward.','footprint',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_330','usr_001','I am home to thousands yet no one built me.','forest',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_331','usr_001','Three paths at the end of one handle.','fork',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_332','usr_001','Red, clever, and always watching.','fox',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_333','usr_001','You cannot buy me, trade me, or command me, yet I am the most valuable thing you own.','friendship',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_334','usr_001','I have not happened yet everyone plans for me.','future',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_335','usr_001','Billions of suns dance in my arms.','galaxy',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_336','usr_001','I am what remains after you take what you need.','garbage',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_337','usr_001','I grow what you plant and what you don''t.','garden',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_338','usr_001','Peel away my white skin and I will make your food sing.','garlic',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_339','usr_001','I stand open to welcome or shut to protect.','gate',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_340','usr_001','I am seen by those who believe and missed by those who don''t.','ghost',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_341','usr_001','Wrapped in paper, I hold a secret until opened.','gift',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_342','usr_001','I move slower than any river yet carve valleys deeper than any blade.','glacier',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_343','usr_001','I bring things together that otherwise would fall apart.','glue',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_344','usr_001','I climb what others cannot and eat what others will not.','goat',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_345','usr_001','I am never born of truth, yet I travel further than any news.','gossip',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_346','usr_001','I have no bottom. Pour into me forever and I will never say enough.','greed',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_347','usr_001','Six strings and a hollow body that sings when touched.','guitar',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_348','usr_001','I strike hard but am guided by gentler hands.','hammer',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_349','usr_001','Ships rest within me after long journeys.','harbor',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_350','usr_001','I sit atop yet never own the head below.','hat',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_351','usr_001','High in the sky, nothing escapes my gaze.','hawk',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_352','usr_001','I am made by the smallest workers and coveted by the largest.','honey',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_353','usr_001','I cost nothing yet sustain millions.','hope',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_354','usr_001','I am a pain that tells you to act.','hunger',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_355','usr_001','I spin to destroy and move to leave silence.','hurricane',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_356','usr_001','I weigh nothing yet can change everything.','idea',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_357','usr_001','Water surrounds me on all sides yet I am not drowning.','island',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_358','usr_001','I keep some in and others out, and both would rather not be near me.','jail',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_359','usr_001','Open me and fill me; close me and keep.','jar',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_360','usr_001','I have a start and an end but the middle is what matters.','journey',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_361','usr_001','Thick with life, loud with sound, hard to enter and harder to leave.','jungle',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_362','usr_001','I bend so you can kneel, run, and climb.','knee',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_363','usr_001','I am sharper than words and can cut either way.','knife',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_364','usr_001','I am still water that sees the sky above.','lake',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_365','usr_001','Soft and white, I follow where I am led.','lamb',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_366','usr_001','I am loudest in company and weakest alone.','laughter',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_367','usr_001','I do nothing and encourage you to do the same.','laziness',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_368','usr_001','Yellow and sour, squeeze me for a drink that makes your face pucker.','lemon',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_369','usr_001','I arrive before my voice and leave before you know I was there.','lightning',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_370','usr_001','I rule without a crown and roar without words.','lion',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_371','usr_001','Two doors that open for words, food, and kisses.','lips',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_372','usr_001','I bask in the sun and lose my tail to save my life.','lizard',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_373','usr_001','I visit those who are surrounded by crowds.','loneliness',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_374','usr_001','Neither earned nor deserved, I arrive without announcement.','luck',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_375','usr_001','I attract without asking and repel without touching.','magnet',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_376','usr_001','I am a problem you walk through.','maze',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_377','usr_001','Open and green, I lie between the forest and the sky.','meadow',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_378','usr_001','The hour when today becomes tomorrow.','midnight',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_379','usr_001','White as snow, I come from living creatures and feed the young.','milk',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_380','usr_001','I teach more than any teacher but no one wants me.','mistake',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_381','usr_001','I swing above the ground, copy what I see, and never touch the floor.','monkey',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_382','usr_001','I am drawn to light even when it destroys me.','moth',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_383','usr_001','I speak, I chew, I taste, yet I forget most of what I say.','mouth',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_384','usr_001','Rain and earth become me together.','mud',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_385','usr_001','I am the question with no certain answer.','mystery',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_386','usr_001','I follow day like a shadow follows light.','night',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_387','usr_001','I visit you when you sleep and leave before you wake.','nightmare',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_388','usr_001','I hold more secrets than all libraries combined.','ocean',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_389','usr_001','Small and bitter alone, yet I am the soul of Mediterranean meals.','olive',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_390','usr_001','I am a path with no beginning, traveled endlessly.','orbit',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_391','usr_001','Invisible, tasteless, and yet every living thing depends on me.','oxygen',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_392','usr_001','I am the alarm your body sounds when something is wrong.','pain',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_393','usr_001','I house the powerful and impress the humble.','palace',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_394','usr_001','I have no branches, only a crown, and I bend in the wind but never break.','palm',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_395','usr_001','I am the ability to wait without complaint.','patience',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_396','usr_001','I arrive after the battle and depart when it begins again.','peace',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_397','usr_001','I am small but I make grown men sneeze.','pepper',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_398','usr_001','I have no body but I announce my presence to everyone nearby.','perfume',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_399','usr_001','Small as a needle, yet I hold two things together.','pin',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_400','usr_001','I stay green when all around me turns brown.','pine',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_401','usr_001','I circle a star and am circled by a moon.','planet',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_402','usr_001','I am a secret room inside your clothes.','pocket',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_403','usr_001','In large doses I kill; in small doses I may cure.','poison',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_404','usr_001','Smaller than a lake, home to frogs and lilies.','pond',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_405','usr_001','I am spoken in a moment and must last a lifetime.','promise',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_406','usr_001','Round and orange, hollow inside, I glow in the dark once carved.','pumpkin',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_407','usr_001','Ask me and I give knowledge; ignore me and stay blind.','question',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_408','usr_001','I once flew, now I write.','quill',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_409','usr_001','White and fast, I vanish in snow.','rabbit',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_410','usr_001','I fall but never bruise, I wet but never drown the sky.','rain',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_411','usr_001','I thrive in shadows and eat what others discard.','rat',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_412','usr_001','I am thinner than paper and sharper than wit.','razor',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_413','usr_001','Beneath the surface I am a city built by tiny creatures.','reef',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_414','usr_001','Billions eat me daily and I began as seeds in water.','rice',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_415','usr_001','I hold what stands above yet I am never seen.','root',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_416','usr_001','Red as blood, hard as stone, prized by kings.','ruby',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_417','usr_001','Time and moisture made me the enemy of iron.','rust',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_418','usr_001','A healed wound that refuses to be forgotten.','scar',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_419','usr_001','I hold many lessons and just as many distractions.','school',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_420','usr_001','I move but stay; I am ancient but never old.','sea',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_421','usr_001','There are four of us and together we make a year.','season',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_422','usr_001','I hold a tree inside my tiny frame.','seed',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_423','usr_001','I never stop moving, I never stop hunting.','shark',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_424','usr_001','I shine like the moon, ring like a bell, and sit between gold and iron.','silver',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_425','usr_001','I have no floor yet I hold everything above.','sky',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_426','usr_001','I live in the air and die in silence.','song',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_427','usr_001','I am the weight felt after joy is gone.','sorrow',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_428','usr_001','I am the smallest version of fire.','spark',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_429','usr_001','I follow the cold and make the sleeping world wake.','spring',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_430','usr_001','I was here before you and will be here long after.','stone',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_431','usr_001','I bring chaos, yet I am made of simple rain and wind.','storm',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_432','usr_001','Hollow from end to end, I let you drink without touching your lips to the glass.','straw',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_433','usr_001','Too small to sail, too persistent to stop.','stream',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_434','usr_001','Sweet in small amounts, dangerous in excess.','sugar',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_435','usr_001','I bring the longest days and the shortest nights.','summer',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_436','usr_001','White and graceful above, paddling furiously below.','swan',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_437','usr_001','I appear when you work hard and vanish when you rest.','sweat',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_438','usr_001','Animals have me but cannot see me without turning around.','tail',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_439','usr_001','Some are born with me, others develop me. None can buy me outright.','talent',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_440','usr_001','Turn me and water appears; turn me again and it disappears.','tap',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_441','usr_001','I fall from the eye in joy and in sorrow.','tear',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_442','usr_001','I shelter the traveler but bow to the wind.','tent',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_443','usr_001','Striped fire that hunts in silence.','tiger',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_444','usr_001','I light the way when the sun cannot.','torch',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_445','usr_001','Buried and sought, I am worth more to the seeker than the finder.','treasure',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_446','usr_001','I lie between two mountains and hold the river.','valley',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_447','usr_001','I live forever but cannot survive the day.','vampire',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_448','usr_001','Wave me and magic happens, but only in the right hands.','wand',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_449','usr_001','I make men bold and keep the coward safe.','wealth',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_450','usr_001','Two become one on my day.','wedding',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_451','usr_001','The largest creature sings beneath the waves.','whale',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_452','usr_001','Ground to dust, I become the bread on your table.','wheat',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_453','usr_001','Softer than a word, louder than silence, and heard only by those near.','whisper',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_454','usr_001','I strip the trees and freeze the lakes.','winter',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_455','usr_001','Speak me to a star; maybe it will listen.','wish',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_456','usr_001','I fly at night and brew by day.','witch',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_457','usr_001','I travel in a pack and speak to the moon.','wolf',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_458','usr_001','I live in the earth and eat what dies.','worm',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_459','usr_001','I am made of seasons and measured in days.','year',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_460','usr_001','I am wasted on the young and mourned by the old.','youth',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_461','usr_001','I tell where you are, but I am not a map.','address',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_462','usr_001','I rise hot and fast, and leave destruction when I cool.','anger',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_463','usr_001','I connect the leg to the foot and bend when you dance.','ankle',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_464','usr_001','I protect the body but slow the wearer.','armor',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_465','usr_001','What fire leaves behind.','ash',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_466','usr_001','Snow given momentum becomes my name.','avalanche',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_467','usr_001','I hold water on one side and money on the other.','bank',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_468','usr_001','I reach out from the trunk but I am not a root.','branch',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_469','usr_001','Sharp and curved, I grip what I catch.','claw',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_470','usr_001','I stand at the edge of land and nothing holds me from the fall.','cliff',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_471','usr_001','Reddish metal that turns green with time.','copper',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_472','usr_001','I hold the newest life and rock it to sleep.','cradle',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_473','usr_001','I stand tall and lift what others cannot reach.','crane',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_474','usr_001','Black as ink, loud as trouble, clever as thieves.','crow',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_475','usr_001','Wings of fire and scales of stone, I rule the sky in stories.','dragon',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_476','usr_001','The moment when day surrenders to night.','dusk',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_477','usr_001','My heat is a sign your body is fighting.','fever',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_478','usr_001','I am light and heat dancing together.','flame',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_479','usr_001','Too much water in the wrong place.','flood',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_480','usr_001','I am a memory stone, the past turned to rock.','fossil',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_481','usr_001','I am the price paid for love that is gone.','grief',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_482','usr_001','I am the reward for months of patience and labor.','harvest',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_483','usr_001','I am the last part of the foot to leave the ground.','heel',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_484','usr_001','I protect the head from what the head cannot see coming.','helmet',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_485','usr_001','I am a song that chases away nightmares before they arrive.','lullaby',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_486','usr_001','Half water, half land, all mystery.','swamp',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL);

-- ── PORTUGUÊS ────────────────────────────────────────────────────────────────
INSERT IGNORE INTO riddles (id, authorId, question, answer, hint, category, difficulty, points, solvedCount, views, isMonthly, isActive, qrCode, tags, monthlyPrize) VALUES
('rdl_pt_287','usr_001','Sou pequena e dura, mas guardo uma floresta dentro de mim.','bolota',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_288','usr_001','Sou a primeira coisa que você aprende, mas nunca falo uma palavra.','alfabeto',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_289','usr_001','Carrego mais que meu peso e nunca reclamo.','formiga',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_290','usr_001','Pinto as árvores de fogo e ouro, depois as desfolho.','outono',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_291','usr_001','Me balanço para dividir o que se ergue alto.','machado',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_292','usr_001','Não sei nada mas sou adorado por todos.','bebê',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_293','usr_001','Me encha de ar e eu subo. Me estoure e desapareço.','balão',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_294','usr_001','Animais dormem entre minhas paredes mas não sou uma casa.','celeiro',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_295','usr_001','Guardo coisas mas tenho buracos nas laterais.','cesta',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_296','usr_001','Cresço no rosto de um homem mas não sou uma planta.','barba',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_297','usr_001','Duas rodas, sem motor, mas te leva longe.','bicicleta',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_298','usr_001','Te mantenho aquecido mas não sinto o frio.','cobertor',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_299','usr_001','Fluo em rios dentro de você mas nunca molho o chão, a não ser em ferimento.','sangue',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_300','usr_001','Duro quando vivo, sobrevivo à carne que me cobria.','osso',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_301','usr_001','Sou o mestre do seu corpo mas nunca dou uma ordem em voz alta.','cérebro',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_302','usr_001','Nasço do grão, moldado por mãos, e morto pela fome.','pão',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_303','usr_001','Comecei como algo feio e me tornei belo sem tentar.','borboleta',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_304','usr_001','Guardo o que voa mas não tenho asas.','gaiola',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_305','usr_001','Sou um quarto sem porta, uma casa sem teto.','caverna',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_306','usr_001','Escrevo de branco e desapareço quando chove.','giz',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_307','usr_001','Não tenho começo nem fim, mas não sou eterno.','círculo',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_308','usr_001','Milhões vivem em mim mas não tenho batimento cardíaco próprio.','cidade',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_309','usr_001','Sou uma armadilha construída pelo menor dos caçadores.','teia de aranha',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_310','usr_001','Viajo bilhões de quilômetros para iluminar brevemente seu céu.','cometa',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_311','usr_001','Todo quarto me tem mas não guardo nada e não custa nada.','canto',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_312','usr_001','Não sou um músculo mas deixo você levantar o que o medo não consegue.','coragem',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_313','usr_001','Sento acima de todos mas não toco o céu.','coroa',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_314','usr_001','Divido o quarto do mundo mas sou fina como papel.','cortina',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_315','usr_001','Nasço à meia-noite e morro da mesma forma.','dia',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_316','usr_001','Fui gasto antes de ser ganho e devo ser devolvido com mais.','dívida',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_317','usr_001','Quanto mais tem, mais sede você sente.','deserto',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_318','usr_001','A pressão me fez e nada pode me quebrar.','diamante',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_319','usr_001','Guardo seus segredos mas não posso falar.','diário',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_320','usr_001','Quanto mais você olha dentro de mim, menos você sabe.','dicionário',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_321','usr_001','Fico entre dois mundos e abro nos dois sentidos.','porta',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_322','usr_001','Mato sem arma e parto sem rastro exceto o silêncio.','seca',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_323','usr_001','Recebo tudo mas não guardo nada.','orelha',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_324','usr_001','Escondo o sol sem tocá-lo.','eclipse',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_325','usr_001','Pareço uma cobra, vivo na água e choco quem me toca.','enguia',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_326','usr_001','Sigo o dia e lidero a noite.','entardecer',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_327','usr_001','Testo sem perguntar se você está pronto.','prova',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_328','usr_001','Fico de pé para dividir mas junto os vizinhos.','cerca',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_329','usr_001','Sou deixada para trás por quem avança.','pegada',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_330','usr_001','Sou lar de milhares mas ninguém me construiu.','floresta',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_331','usr_001','Três caminhos no final de um cabo.','garfo',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_332','usr_001','Vermelha, esperta e sempre observando.','raposa',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_333','usr_001','Não me pode comprar, trocar ou ordenar, mas sou a coisa mais valiosa que você possui.','amizade',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_334','usr_001','Ainda não aconteci mas todos planejam para mim.','futuro',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_335','usr_001','Bilhões de sóis dançam em meus braços.','galáxia',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_336','usr_001','Sou o que resta depois que você pega o que precisa.','lixo',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_337','usr_001','Cultivo o que você planta e o que não planta.','jardim',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_338','usr_001','Descasque minha pele branca e farei sua comida cantar.','alho',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_339','usr_001','Fico aberto para acolher ou fechado para proteger.','portão',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_340','usr_001','Sou visto por quem acredita e ignorado por quem não acredita.','fantasma',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_341','usr_001','Embrulhado em papel, guardo um segredo até ser aberto.','presente',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_342','usr_001','Movo-me mais devagar que qualquer rio mas esculpo vales mais profundos que qualquer lâmina.','glaciar',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_343','usr_001','Uno coisas que de outra forma cairiam separadas.','cola',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_344','usr_001','Escalo o que outros não podem e como o que outros não querem.','cabra',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_345','usr_001','Nunca nasço da verdade, mas viajo mais longe que qualquer notícia.','fofoca',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_346','usr_001','Não tenho fundo. Me encha para sempre e nunca direi basta.','ganância',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_347','usr_001','Seis cordas e um corpo oco que canta quando tocado.','violão',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_348','usr_001','Golpeio com força mas sou guiado por mãos mais gentis.','martelo',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_349','usr_001','Navios descansam em mim após longas viagens.','porto',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_350','usr_001','Sento no topo mas nunca possuo a cabeça abaixo.','chapéu',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_351','usr_001','Lá no alto, nada escapa do meu olhar.','gavião',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_352','usr_001','Sou feito pelos menores trabalhadores e cobiçado pelos maiores.','mel',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_353','usr_001','Não custa nada mas sustenta milhões.','esperança',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_354','usr_001','Sou uma dor que te diz para agir.','fome',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_355','usr_001','Giro para destruir e me movo para deixar silêncio.','furacão',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_356','usr_001','Não peso nada mas posso mudar tudo.','ideia',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_357','usr_001','Água me cerca por todos os lados mas não estou me afogando.','ilha',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_358','usr_001','Mantenho alguns dentro e outros fora, e ambos prefeririam não ficar perto de mim.','cadeia',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_359','usr_001','Me abra e me encha; me feche e preserve.','pote',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_360','usr_001','Tenho um início e um fim mas o meio é o que importa.','jornada',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_361','usr_001','Densa de vida, barulhenta, difícil de entrar e mais difícil de sair.','selva',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_362','usr_001','Me curvo para que você possa ajoelhar, correr e escalar.','joelho',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_363','usr_001','Sou mais afiada que palavras e posso cortar nos dois sentidos.','faca',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_364','usr_001','Sou água parada que enxerga o céu acima.','lago',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_365','usr_001','Macio e branco, sigo onde sou conduzido.','cordeiro',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_366','usr_001','Sou mais alto em companhia e mais fraco sozinho.','riso',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_367','usr_001','Não faço nada e te encorajo a fazer o mesmo.','preguiça',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_368','usr_001','Amarelo e azedo, me esprema para uma bebida que fará seu rosto franzir.','limão',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_369','usr_001','Chego antes da minha voz e parto antes que você saiba que estive aqui.','relâmpago',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_370','usr_001','Reino sem coroa e rujo sem palavras.','leão',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_371','usr_001','Duas portas que se abrem para palavras, comida e beijos.','lábios',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_372','usr_001','Fico ao sol e perco minha cauda para salvar minha vida.','lagarto',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_373','usr_001','Visito aqueles rodeados por multidões.','solidão',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_374','usr_001','Nem ganha nem merecida, chego sem aviso.','sorte',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_375','usr_001','Atraio sem pedir e repilo sem tocar.','ímã',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_376','usr_001','Sou um problema pelo qual você caminha.','labirinto',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_377','usr_001','Aberto e verde, fico entre a floresta e o céu.','prado',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_378','usr_001','A hora em que o hoje se torna amanhã.','meia-noite',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_379','usr_001','Branco como neve, venho de criaturas vivas e alimento os jovens.','leite',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_380','usr_001','Ensino mais que qualquer professor mas ninguém me quer.','erro',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_381','usr_001','Balanceio acima do chão, copio o que vejo e nunca toco o chão da floresta.','macaco',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_382','usr_001','Sou atraída pela luz mesmo quando ela me destrói.','mariposa',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_383','usr_001','Falo, mastigo, provo, mas esqueço a maior parte do que digo.','boca',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_384','usr_001','Chuva e terra se tornam eu juntos.','lama',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_385','usr_001','Sou a pergunta sem resposta certa.','mistério',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_386','usr_001','Sigo o dia como uma sombra segue a luz.','noite',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_387','usr_001','Te visito quando dorme e parto antes que acorde.','pesadelo',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_388','usr_001','Guardo mais segredos do que todas as bibliotecas juntas.','oceano',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_389','usr_001','Pequena e amarga sozinha, mas sou a alma das refeições mediterrâneas.','azeitona',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_390','usr_001','Sou um caminho sem início, percorrido sem fim.','órbita',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_391','usr_001','Invisível, insípido, mas todo ser vivo depende de mim.','oxigênio',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_392','usr_001','Sou o alarme que seu corpo dispara quando algo está errado.','dor',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_393','usr_001','Abrico os poderosos e impressiono os humildes.','palácio',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_394','usr_001','Não tenho galhos, apenas uma copa, e me curvo no vento mas nunca quebro.','palmeira',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_395','usr_001','Sou a habilidade de esperar sem reclamar.','paciência',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_396','usr_001','Chego após a batalha e parto quando ela começa de novo.','paz',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_397','usr_001','Sou pequena mas faço homens adultos espirrar.','pimenta',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_398','usr_001','Não tenho corpo mas anuncio minha presença a todos próximos.','perfume',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_399','usr_001','Pequeno como uma agulha, mas uno duas coisas.','alfinete',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_400','usr_001','Permaneço verde quando tudo ao meu redor fica marrom.','pinheiro',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_401','usr_001','Circulo uma estrela e sou circulado por uma lua.','planeta',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_402','usr_001','Sou um quarto secreto dentro das suas roupas.','bolso',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_403','usr_001','Em grandes doses mato; em pequenas doses posso curar.','veneno',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_404','usr_001','Menor que um lago, lar de rãs e lírios.','lagoa',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_405','usr_001','Sou dita em um momento e devo durar uma vida.','promessa',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_406','usr_001','Redonda e laranja, oca por dentro, brilho no escuro uma vez esculpida.','abóbora',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_407','usr_001','Me faça e dou conhecimento; me ignore e fique cego.','pergunta',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_408','usr_001','Uma vez voei, agora escrevo.','pena',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_409','usr_001','Branco e rápido, desapareço na neve.','coelho',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_410','usr_001','Caio mas nunca machuco, molho mas nunca afogo o céu.','chuva',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_411','usr_001','Prospero nas sombras e como o que outros descartam.','rato',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_412','usr_001','Sou mais fino que papel e mais afiado que o raciocínio.','navalha',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_413','usr_001','Abaixo da superfície sou uma cidade construída por minúsculas criaturas.','recife',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_414','usr_001','Bilhões me comem diariamente e comecei como sementes na água.','arroz',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_415','usr_001','Sustento o que está acima mas nunca sou visto.','raiz',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_416','usr_001','Vermelho como sangue, duro como pedra, valorizado por reis.','rubi',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_417','usr_001','O tempo e a umidade me tornaram o inimigo do ferro.','ferrugem',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_418','usr_001','Uma ferida curada que se recusa a ser esquecida.','cicatriz',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_419','usr_001','Guardo muitas lições e igualmente muitas distrações.','escola',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_420','usr_001','Movo-me mas fico; sou antigo mas nunca velho.','mar',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_421','usr_001','Somos quatro e juntos formamos um ano.','estação',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_422','usr_001','Guardo uma árvore dentro do meu minúsculo corpo.','semente',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_423','usr_001','Nunca paro de me mover, nunca paro de caçar.','tubarão',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_424','usr_001','Brilho como a lua, ressoo como um sino, e sento entre o ouro e o ferro.','prata',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_425','usr_001','Não tenho chão mas sustento tudo acima.','céu',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_426','usr_001','Vivo no ar e morro no silêncio.','canção',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_427','usr_001','Sou o peso sentido depois que a alegria se vai.','tristeza',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_428','usr_001','Sou a menor versão do fogo.','faísca',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_429','usr_001','Sigo o frio e faço o mundo adormecido acordar.','primavera',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_430','usr_001','Estava aqui antes de você e estarei aqui muito depois.','pedra',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_431','usr_001','Trago o caos, mas sou feita de simples chuva e vento.','tempestade',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_432','usr_001','Oco de ponta a ponta, deixo você beber sem encostar os lábios no copo.','canudo',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_433','usr_001','Pequeno demais para navegar, persistente demais para parar.','riacho',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_434','usr_001','Doce em pequenas quantidades, perigoso em excesso.','açúcar',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_435','usr_001','Trago os dias mais longos e as noites mais curtas.','verão',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_436','usr_001','Branco e gracioso acima, pedalando furiosamente abaixo.','cisne',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_437','usr_001','Apareço quando você trabalha duro e desapareço quando descansa.','suor',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_438','usr_001','Os animais me têm mas não podem me ver sem se virar.','cauda',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_439','usr_001','Alguns nascem comigo, outros me desenvolvem. Ninguém pode me comprar diretamente.','talento',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_440','usr_001','Me gire e a água aparece; me gire novamente e ela desaparece.','torneira',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_441','usr_001','Caio do olho na alegria e na tristeza.','lágrima',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_442','usr_001','Abrico o viajante mas me curvo ao vento.','barraca',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_443','usr_001','Fogo listrado que caça em silêncio.','tigre',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_444','usr_001','Ilumino o caminho quando o sol não pode.','tocha',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_445','usr_001','Enterrado e procurado, valho mais para quem busca do que para quem encontra.','tesouro',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_446','usr_001','Fico entre duas montanhas e sustento o rio.','vale',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_447','usr_001','Vivo para sempre mas não sobrevivo ao dia.','vampiro',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_448','usr_001','Me agite e a magia acontece, mas apenas nas mãos certas.','varinha',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_449','usr_001','Faço os homens ousados e mantenho o covarde seguro.','riqueza',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_450','usr_001','Dois se tornam um no meu dia.','casamento',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_451','usr_001','A maior criatura canta abaixo das ondas.','baleia',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_452','usr_001','Moído ao pó, me torno o pão na sua mesa.','trigo',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_453','usr_001','Mais suave que uma palavra, mais alto que o silêncio, e ouvido apenas pelos que estão perto.','sussurro',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_454','usr_001','Desfolho as árvores e congelo os lagos.','inverno',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_455','usr_001','Me fale a uma estrela; talvez ela ouça.','desejo',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_456','usr_001','Voo à noite e preparo poções de dia.','bruxa',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_457','usr_001','Viajo em bando e falo com a lua.','lobo',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_458','usr_001','Vivo na terra e como o que morre.','minhoca',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_459','usr_001','Sou feito de estações e medido em dias.','ano',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_460','usr_001','Sou desperdiçada pelos jovens e lamentada pelos velhos.','juventude',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_461','usr_001','Digo onde você está, mas não sou um mapa.','endereço',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_462','usr_001','Subo quente e rápido, e deixo destruição quando esfrio.','raiva',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_463','usr_001','Conecto a perna ao pé e me curvo quando você dança.','tornozelo',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_464','usr_001','Protejo o corpo mas deixo o portador mais lento.','armadura',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_465','usr_001','O que o fogo deixa para trás.','cinzas',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_466','usr_001','A neve com impulso se torna meu nome.','avalanche',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_467','usr_001','Guardo água de um lado e dinheiro do outro.','banco',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_468','usr_001','Estendo-me do tronco mas não sou uma raiz.','galho',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_469','usr_001','Afiada e curva, seguro o que apanho.','garra',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_470','usr_001','Fico na beira da terra e nada me segura da queda.','penhasco',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_471','usr_001','Metal avermelhado que fica verde com o tempo.','cobre',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_472','usr_001','Guardo a vida mais nova e a embalo para dormir.','berço',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_473','usr_001','Me ponho de pé para carregar o que outros não conseguem levantar.','guindaste',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_474','usr_001','Negro como tinta, barulhento como confusão, esperto como ladrão.','corvo',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_475','usr_001','Asas de fogo e escamas de pedra, reino o céu nas histórias.','dragão',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_476','usr_001','O momento em que o dia se rende à noite.','crepúsculo',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_477','usr_001','Meu calor é sinal de que seu corpo está lutando.','febre',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_478','usr_001','Sou luz e calor dançando juntos.','chama',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_479','usr_001','Água demais no lugar errado.','enchente',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_480','usr_001','Sou uma pedra de memória, o passado transformado em rocha.','fóssil',NULL,'natureza',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_481','usr_001','Sou o preço pago pelo amor que foi embora.','luto',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_482','usr_001','Sou a recompensa de meses de paciência e trabalho.','colheita',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_483','usr_001','Sou a última parte do pé a sair do chão.','calcanhar',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_484','usr_001','Protejo a cabeça do que a cabeça não consegue ver chegando.','capacete',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_485','usr_001','Sou uma canção que afasta os pesadelos antes que cheguem.','ninar',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_486','usr_001','Metade água, metade terra, total mistério.','pântano',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL);
