-- ==============================================================================
-- MAGOS PLATFORM - Riddles Seed PT-BR (traduzido e adaptado de riddles_seed.sql)
-- Trocadilhos intraduzíveis foram adaptados para equivalentes em português
-- Total: 286 riddles | authorId: usr_001
-- ==============================================================================

INSERT IGNORE INTO riddles (id, authorId, question, answer, hint, category, difficulty, points, solvedCount, views, isMonthly, isActive, qrCode, tags, monthlyPrize) VALUES
('rdl_pt_001','usr_001','Quase todo mundo precisa, pede e dá. Mas quase ninguém aceita.','conselho',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_002','usr_001','O que sobe mas nunca desce?','idade',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_003','usr_001','Morra sem mim, nunca me agradeça. Caminhe por mim, nunca me sinta.','ar',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_004','usr_001','Hoje ele está lá para te fazer tropeçar. E te atormentará amanhã.','álcool',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_005','usr_001','O que você joga para usar e recolhe quando termina?','âncora',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_006','usr_001','Sou muito tentadora, dizem por aí. Tenho um casaco brilhante e vermelho.','maçã',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_007','usr_001','Tenho muitas penas para me ajudar a voar. Tenho um corpo e uma cabeça.','flecha',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_008','usr_001','Posso ser movida. Posso ser rolada. Mas nada vou segurar.','bola',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_009','usr_001','Às vezes verdes. Às vezes amarelas.','bananas',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_010','usr_001','Durmo de dia, voo de noite. Não tenho penas para ajudar meu voo.','morcego',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_011','usr_001','Sou a barra amarela da saia azul do mar.','praia',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_012','usr_001','À noite uma montanha, de manhã um prado.','cama',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_013','usr_001','Um guerreiro entre as flores, carrega uma espada afiada.','abelha',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_014','usr_001','Milhares guardam ouro nesta casa.','colmeia',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_015','usr_001','Redondo como um botão, fundo como um poço.','sino',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_016','usr_001','Sou o melhor amigo do fogo. Quando gordo, meu corpo se enche de vento.','fole',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_017','usr_001','Você ganha muitos de mim, mas nunca o suficiente.','aniversário',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_018','usr_001','Sou visto na água. Se visto no céu, estou no arco-íris.','azul',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_019','usr_001','Minha vida é frequentemente um volume de tristeza, sua ajuda é necessária.','livro',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_020','usr_001','Nos coloca de costas e abre nossos estômagos.','livros',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_021','usr_001','Ouvi falar de uma maravilha, de palavras roídas por traças.','traça',NULL,'animais',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_022','usr_001','Dois irmãos somos nós, grandes fardos carregamos.','botas',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_023','usr_001','Tenho pescoço mas não tenho cabeça. Tenho corpo mas não tenho braço.','garrafa',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_024','usr_001','Leve como uma pena, mas você não consegue me segurar por dez minutos.','respiração',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_025','usr_001','Para atravessar a água sou o caminho, sobre a água estou.','ponte',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_026','usr_001','Tenho cem pernas, mas não consigo me firmar.','vassoura',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_027','usr_001','Um murmúrio grave foi ouvido do curral.','touro',NULL,'animais',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_028','usr_001','O que jaz num túnel de escuridão. Que só pode atacar quando puxado para trás?','bala',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_029','usr_001','Plano como uma folha, redondo como um anel. Tem dois olhos mas não pode ver nada.','botão',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_030','usr_001','Tenho um olho. Vejo de perto e de longe. Guardo os momentos que você ama.','câmera',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_031','usr_001','Minha vida pode ser medida em horas. Sirvo sendo devorada.','vela',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_032','usr_001','O que tem 13 corações mas nenhum bate?','baralho',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_033','usr_001','Que tipo de cobertura nunca sai do chão?','tapete',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_034','usr_001','Auréola de água, língua de madeira. Pele de pedra, há muito estou de pé.','castelo',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_035','usr_001','Furtivo como uma sombra na escuridão da noite, astuto mas afetuoso.','gato',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_036','usr_001','Não sou nada mais do que buracos ligados a mais buracos.','corrente',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_037','usr_001','Tenho pernas mas não ando, costas fortes mas não trabalho.','cadeira',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_038','usr_001','O que é preto quando você pega, vermelho quando usa?','carvão vegetal',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_039','usr_001','Não nascido, mas tirado do corpo da mãe.','queijo',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_040','usr_001','Visto uma roupa vermelha, com cajado na mão e uma pedra na garganta.','cereja',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_041','usr_001','Uma dança lenta e solene de guerreiros fingindo golpes.','xadrez',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_042','usr_001','O que é tal que dado um, você terá dois ou nenhum?','escolha',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_043','usr_001','Esta coisa corre mas não anda, às vezes canta mas nunca fala.','relógio',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_044','usr_001','Voo, mas não tenho asas. Choro, mas não tenho olhos.','nuvem',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_045','usr_001','O que é preto de manhã e vermelho à tarde?','carvão mineral',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_046','usr_001','Uma pequena piscina com duas camadas de parede ao redor.','coco',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_047','usr_001','O homem que o fez não precisava dele.','caixão',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_048','usr_001','Tenho dois lados mas carrego apenas um. Não tenho pernas mas viajo muito.','moeda',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_049','usr_001','O que você pode pegar mas não pode jogar?','resfriado',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_050','usr_001','Posso ser de metal ou osso, tenho muitos dentes.','pente',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_051','usr_001','Sou tão simples que só posso apontar.','bússola',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_052','usr_001','Você joga fora a parte de fora e cozinha a parte de dentro.','milho',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_053','usr_001','Quem o faz não o conta.','falsificação',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_054','usr_001','Quanto mais tem, menos você vê.','escuridão',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_055','usr_001','Quinhentos o começam, quinhentos o terminam.','davi',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_056','usr_001','Alguns tentam se esconder, outros tentam trapacear.','morte',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_057','usr_001','O que é colocado na mesa, cortado, mas nunca comido?','baralho',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_058','usr_001','Escavo pequenas cavernas e guardo ouro e prata nelas.','dentista',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_059','usr_001','Você me encontrará com quatro pernas, mas sem cabelo.','escrivaninha',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_060','usr_001','Uma gotinha minúscula, como vidro frágil, enfileirada ao longo de um fio de grama.','orvalho',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_061','usr_001','O que tem seis faces e vinte e um olhos?','dado',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_062','usr_001','O que usa casaco no inverno e calça no verão?','cachorro',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_063','usr_001','Mãos ela tem mas não segura. Dentes ela tem mas não morde.','boneca',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_064','usr_001','Que tipo de rosquinha é vazia no centro e não tem casca?','rosquinha',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_065','usr_001','Uma palavra eu conheço, seis letras ela contém.','dúzias',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_066','usr_001','Isso está no reino do verdadeiro e no reino do falso.','sonho',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_067','usr_001','Embora minha vaca esteja morta, ainda a bato. Que barulhão ela faz!','tambor',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_068','usr_001','As pessoas são contratadas para me eliminar.','poeira',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_069','usr_001','Sou o terceiro de um brilho cintilante, prospero por toda parte.','terra',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_070','usr_001','Você me ouviu antes, mas me ouve novamente, depois morro.','eco',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_071','usr_001','O que precisa ser quebrado antes de ser usado?','ovo',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_072','usr_001','Flutuo para sempre com a corrente por esses longos canais.','eletricidade',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_073','usr_001','Rosto com uma árvore, pele como o mar. Sou uma grande besta.','elefante',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_074','usr_001','Que palavra começa com E, termina com E, mas só tem uma letra?','envelope',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_075','usr_001','Vejo tudo, mas nunca me vejo.','olho',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_076','usr_001','Dois cavalos, os mais velozes, atrelados em par.','olhos',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_077','usr_001','Quando solto, voo embora. Nunca tão maldito quanto quando me perco.','peido',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_078','usr_001','Está na sua mão, mas você não consegue sentir.','destino',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_079','usr_001','Faço você fraco nos piores momentos.','medo',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_080','usr_001','Sou os dedos estendidos que agarram e seguram o vento.','pena',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_081','usr_001','Conheço uma palavra de três letras. Acrescente duas e haverá menos!','pouco',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_082','usr_001','Comprido e fino, vermelho por dentro, com uma unha na ponta.','dedo',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_083','usr_001','Me alimente e vivo, me dê água e morro.','fogo',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_084','usr_001','Gritando, voando, buscando o céu. Flores de fogo voando alto.','fogos de artifício',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_085','usr_001','Vivo sem respirar, frio como a morte, vestido de malha sem tinir.','peixe',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_086','usr_001','Marcho à frente dos exércitos, mil me saúdam.','bandeira',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_087','usr_001','Quando são capturadas, são jogadas fora.','pulgas',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_088','usr_001','Mil dobras coloridas se esticam em direção ao céu.','flor',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_089','usr_001','Quem passa o dia na janela e vai à mesa para as refeições?','mosca',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_090','usr_001','Meu segundo é executado pelo meu primeiro, e é considerado um ladrão.','passo',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_091','usr_001','Borbulho, rio e cuspo água no seu rosto.','fonte',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_092','usr_001','Tenho quatro pernas mas não tenho rabo. Geralmente sou ouvido apenas à noite.','sapo',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_093','usr_001','Passa por todos os morros e vales. Morde forte, mas nunca engole.','geada',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_094','usr_001','Nascido da terra, mas sem nenhuma de sua força.','vidro',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_095','usr_001','Sem brida, sem sela, ando sobre uma coisa a cavaleiro.','óculos',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_096','usr_001','O que você enche com as mãos vazias?','luvas',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_097','usr_001','Faço os homens enlouquecerem de amor por mim. Facilmente vencido, nunca livre.','ouro',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_098','usr_001','O sol as assa, a mão as esmaga, o pé as pisa.','uvas',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_099','usr_001','A lâmina fina e afiada, que corta o vento.','grama',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_100','usr_001','Tão frio, úmido e escuro este lugar.','tumba',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_101','usr_001','Podem ser guardados, mas poucos retêm água.','rancor',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_102','usr_001','Longo e escorregadio como uma truta, nunca canta até suas entranhas saírem.','arma',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_103','usr_001','Eu tenho um, você tem um.','hábito',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_104','usr_001','O que está sobre a cabeça e sob o chapéu?','cabelo',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_105','usr_001','Dois em um todo e quatro em um par.','metade',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_106','usr_001','Até onde um cachorro cego caminha numa floresta?','metade do caminho',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_107','usr_001','São muitas e uma, acenam e batem.','mãos',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_108','usr_001','Dentro de uma casa em chamas, isso é melhor de se fazer.','pressa',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_109','usr_001','Você pode rolar nele, queimá-lo, os animais o comem.','feno',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_110','usr_001','Sou a fonte de todas as emoções, mas estou presa numa prisão branca.','coração',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_111','usr_001','O que fica maior quanto mais você tira dele?','buraco',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_112','usr_001','Quando você para e olha, sempre pode me ver.','horizonte',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_113','usr_001','O que sempre vai para a cama com os sapatos?','cavalo',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_114','usr_001','Dois corpos tenho, embora ambos unidos em um.','ampulheta',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_115','usr_001','Força suficiente para destruir navios e esmagar telhados.','gelo',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_116','usr_001','Mais leve do que o material de que sou feito, mais de mim está escondido.','iceberg',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_117','usr_001','Pontos brilhantes que apontam para baixo.','sincelo',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_118','usr_001','Guardo a tinta para o escritor e fico sobre a mesa.','tinteiro',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_119','usr_001','Arrancado do ventre da minha mãe. Batido e queimado, me torno.','ferro',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_120','usr_001','Posso ser feita, posso ser contada.','piada',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_121','usr_001','Corto o mal como uma espada de dois gumes.','justiça',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_122','usr_001','O que força e resistência não conseguem atravessar?','chave',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_123','usr_001','O que passa pela porta mas nunca entra?','buraco da fechadura',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_124','usr_001','Inútil para um, bênção para dois.','beijo',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_125','usr_001','Adoro dançar, girar e brincar.','pipa',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_126','usr_001','Teto de ferro, paredes de vidro, queima e queima e nunca cai.','lanterna',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_127','usr_001','Sou a língua vermelha da terra, que enterra cidades.','lava',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_128','usr_001','Caminhe sobre os vivos, eles nem sequer murmuram.','folhas',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_129','usr_001','Não respiro, mas corro e salto.','perna',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_130','usr_001','Que prédio tem mais histórias?','biblioteca',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_131','usr_001','Às vezes sou branca e sempre errada.','mentira',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_132','usr_001','O que pode encher uma sala mas não ocupa espaço?','luz',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_133','usr_001','O que entra na água preto e sai vermelho?','lagosta',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_134','usr_001','Uma adaga cravada no meu próprio coração dita o caminho que sigo.','cadeado',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_135','usr_001','No fogo você me ouve gritar, rangendo e gemendo.','tronco',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_136','usr_001','O que pode tocar alguém uma vez e durar a vida toda?','amor',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_137','usr_001','Tenho rios sem água.','mapa',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_138','usr_001','Ferramenta do ladrão, brinquedo da rainha.','máscara',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_139','usr_001','Tire um e coce minha cabeça, agora sou preto mas antes era vermelho.','fósforo',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_140','usr_001','O que pode trazer os mortos de volta. Nos fazer chorar, nos fazer rir?','memória',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_141','usr_001','Sou um deus. Sou um planeta. Meço calor.','mercúrio',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_142','usr_001','Algo completamente irreal, mas que parece real para mim.','mente',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_143','usr_001','Olho para você, você olha para mim, levanto minha direita.','espelho',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_144','usr_001','Morro cheio, buraco cheio, mas você não consegue pegar uma tigela cheia.','névoa',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_145','usr_001','O que vai mais longe quanto mais devagar vai?','dinheiro',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_146','usr_001','Sempre velha, às vezes nova. Nunca triste, às vezes azul.','lua',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_147','usr_001','Tem raízes que ninguém vê, é mais alto que as árvores.','montanha',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_148','usr_001','Que tipo de sala não tem janelas nem portas?','cogumelo',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_149','usr_001','Ao meu som, um pode sonhar ou bater o pé.','música',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_150','usr_001','Quem trabalha quando brinca e brinca quando trabalha?','músico',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_151','usr_001','Me escondo, mas minha cabeça fica de fora.','prego',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_152','usr_001','O que foi dado a você e pertence apenas a você?','nome',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_153','usr_001','Um cavalo de ferro com uma cauda de linho.','agulha',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_154','usr_001','Uma casa de madeira em um lugar escondido.','ninho',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_155','usr_001','Segure o rabo, enquanto pesco para você.','rede',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_156','usr_001','Posso ser escrita, falada, exposta.','notícia',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_157','usr_001','Às vezes sou alto. E visto com desagrado.','barulho',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_158','usr_001','Que palavra é igual lida de trás para frente?','ovo',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_159','usr_001','Elimina os maus, altos e baixos.','laço',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_160','usr_001','Posso correr mas não andar. Onde quer que eu vá, o pensamento me segue.','nariz',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_161','usr_001','O que o homem ama mais do que a vida, teme mais do que a morte?','nada',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_162','usr_001','Uma casinha cheia de carne, sem porta para entrar e comer.','noz',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_163','usr_001','Sou a fonte de que ninguém pode beber.','óleo',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_164','usr_001','Tire minha pele, eu não chorarei, mas você chorará.','cebola',NULL,'alimentos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_165','usr_001','Ouro numa bolsa de couro, balançando numa árvore.','laranja',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_166','usr_001','O que pergunta mas nunca responde?','coruja',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_167','usr_001','Guarda mais conhecimento do que jamais foi dito.','papel',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_168','usr_001','Na metade do caminho morro colina acima, finalmente te vejo.','passado',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_169','usr_001','Somos oito e nos movemos para frente e para trás.','peões',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_170','usr_001','Uma semente sou eu, sete letras formam meu nome.','ervilha',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_171','usr_001','A criatura mais estranha que você já verá.','pavão',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_172','usr_001','Uma casa com dois ocupantes, às vezes um.','amendoim',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_173','usr_001','Linda e redonda, brilho com luz pálida.','pérola',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_174','usr_001','Sou a ferramenta que inspira muitos.','caneta',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_175','usr_001','Geralmente uso um casaco amarelo.','lápis',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_176','usr_001','O que tem cabeça, cauda, é marrom e não tem pernas?','moeda',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_177','usr_001','Uma mulher fotografa o marido, depois o revela na água.','foto',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_178','usr_001','Sou uma caixa que guarda teclas sem fechaduras.','piano',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_179','usr_001','O que perde a cabeça de manhã?','travesseiro',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_180','usr_001','O que faz muito barulho ao trocar de casaco?','pipoca',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_181','usr_001','Tenho uma pele, mais olhos do que um.','batata',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_182','usr_001','O que pode ser engolido, mas também pode te engolir?','orgulho',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_183','usr_001','Casou com muitas mulheres mas nunca se casou.','padre',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_184','usr_001','Brinco com as palavras e confundo muitos.','trocadilho',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_185','usr_001','Luzes diferentes me tornam estranho, mudando de tamanho.','pupila',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_186','usr_001','Apenas dois espinhos e milhares de costelas.','ferrovia',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_187','usr_001','Dividi o um em cinco.','arco-íris',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_188','usr_001','Quebre e é melhor, imediatamente definido e mais forte.','recorde',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_189','usr_001','Você não pode ver nada mais, quando olha para o meu rosto.','reflexo',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_190','usr_001','O que pode ser ouvido e capturado mas nunca visto?','comentário',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_191','usr_001','Para me desvendar você precisa de uma chave simples.','enigma',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_192','usr_001','Não tem topo nem fundo, mas pode segurar carne e ossos.','anel',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_193','usr_001','O que sempre corre mas nunca anda, frequentemente murmura?','rio',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_194','usr_001','Corro por colinas. Desvio por montanhas.','estrada',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_195','usr_001','Força de dez homens, comprimento de dez homens.','corda',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_196','usr_001','O que pode queimar os olhos e picar a boca?','sal',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_197','usr_001','Construo castelos. Derrubos montanhas.','areia',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_198','usr_001','Amarro e ele anda. Solto e ele para.','sandália',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_199','usr_001','Meus dentes são afiados, minha espinha é reta.','serra',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_200','usr_001','Abro bem e fecho com firmeza, sou afiada.','tesoura',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_201','usr_001','Se você tem, quer compartilhar.','segredo',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_202','usr_001','Alto de manhã, baixo ao meio-dia, desaparecido à noite.','sombra',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_203','usr_001','Dessas coisas, eu tenho duas.','compartilhar',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_204','usr_001','Peso na barriga, árvores nas costas.','navio',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_205','usr_001','O que tem pescoço mas não tem cabeça, dois braços mas não tem mãos?','camisa',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_206','usr_001','Corre por campos e florestas o dia todo.','sapato',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_207','usr_001','Em fivelas ou cadarços, eles ajudam a definir o ritmo.','sapatos',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_208','usr_001','Que palavra de cinco letras fica mais curta quando você acrescenta mais letras?','curto',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_209','usr_001','O que é redondo como uma frigideira, fundo como uma banheira?','peneira',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_210','usr_001','O que é tão frágil que dizer seu nome o quebra?','silêncio',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_211','usr_001','O irmão de um mendigo foi ao mar e se afogou.','irmã',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_212','usr_001','Dobra meu número, sou menor que uma vintena.','seis',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_213','usr_001','Sou inteiro mas incompleto. Não tenho olhos, mas vejo.','esqueleto',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_214','usr_001','Quando líquido me espirra, nada penetra.','pele',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_215','usr_001','Enfraqueço todos os homens por horas cada dia.','sono',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_216','usr_001','Uma milha de ponta a ponta, mas tão próximo quanto um amigo.','sorriso',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_217','usr_001','Casa cheia, quintal cheio, chaminé cheia.','fumaça',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_218','usr_001','Se um homem carregasse meu fardo, quebraria suas costas.','caracol',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_219','usr_001','Posso chicotar como bacon, sou feita com um ovo.','cobra',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_220','usr_001','Pássaro branco, sem penas, voando do paraíso.','neve',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_221','usr_001','Vi um homem de branco, que visão estranha.','boneco de neve',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_222','usr_001','Você o usa entre a cabeça e os dedos dos pés.','sabonete',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_223','usr_001','Não posso ser sentida, vista ou tocada.','alma',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_224','usr_001','O que envolve o mundo, mas cabe dentro de um dedal?','espaço',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_225','usr_001','Um monstro horrendo se esconde do dia, com muitas pernas.','aranha',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_226','usr_001','Fui à floresta e o peguei.','farpa',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_227','usr_001','Estou cheia de buracos, mas cheia de água.','esponja',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_228','usr_001','Viajamos muito, mas somos prisioneiros.','esporas',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_229','usr_001','Um quebra-nozes lá em cima na árvore.','esquilo',NULL,'animais',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_230','usr_001','Sou todo, sou seguro, abrigo cavalos.','estábulo',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_231','usr_001','Tenho asas mas não voo, artistas se apresentam sobre mim.','palco',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_232','usr_001','Sobre mim você pode pisar, suavemente sob cobertura.','escada',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_233','usr_001','O que vai ao redor do mundo e fica num canto?','selo',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_234','usr_001','Com presas afiadas fica à espera.','grampeador',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_235','usr_001','À noite apareço sem ser chamado.','estrelas',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_236','usr_001','Quanto mais você dá, mais deixa para trás.','passos',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_237','usr_001','Quatro de nós estamos no seu campo.','naipes',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_238','usr_001','O que passa pela porta sem se apertar?','sol',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_239','usr_001','Apareço de manhã. Mas estou sempre lá.','luz do sol',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_240','usr_001','Dormindo durante o dia, me escondo.','amanhecer',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_241','usr_001','O dente de um dragão na mão de um mortal.','espada',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_242','usr_001','Ele tem uma e uma pessoa tem duas.','sílaba',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_243','usr_001','Nas tardes, frequentemente me banho.','sachê de chá',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_244','usr_001','Tenho bico para verter e barriga para guardar água quente.','bule',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_245','usr_001','Trinta cavalos brancos numa colina vermelha.','dentes',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_246','usr_001','Você deve guardar esta coisa.','temperamento',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_247','usr_001','O que frequentemente é devolvido, mas nunca emprestado?','gratidão',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_248','usr_001','O que você não pode ver, ouvir ou sentir, até ser tarde demais?','ladrão',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_249','usr_001','Um barril aberto, em forma de colmeia.','dedal',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_250','usr_001','Andei e andei e por fim o peguei.','espinho',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_251','usr_001','Usado à esquerda ou à direita, viajo sobre paralelepípedos.','polegar',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_252','usr_001','Sem pai, sem mãe. Nascido sem pecado.','trovão',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_253','usr_001','Quando o dia depois de amanhã for ontem.','quinta-feira',NULL,'abstrato',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_254','usr_001','Entramos, saímos. Ao redor e em fila.','marés',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_255','usr_001','Tenho dois significados para mim.','gravata',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_256','usr_001','Esta coisa devora tudo.','tempo',NULL,'abstrato',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_257','usr_001','Nunca fui, sempre serei.','amanhã',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_258','usr_001','Para frente sou pesado, para trás não.','tonelada',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_259','usr_001','Frequentemente segurada mas nunca tocada.','língua',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_260','usr_001','Me uso para polir os cavalinhos de marfim da sua boca.','pasta de dente',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_261','usr_001','O que fica mais molhado quanto mais seca?','toalha',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_262','usr_001','Erguendo-me rigidamente para o céu, mostro meus dedos.','árvore',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_263','usr_001','Criaturas de poder, criaturas de porte.','árvores',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_264','usr_001','Quem rema rapidamente com quatro remos?','tartaruga',NULL,'animais',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_265','usr_001','O que sobe quando a chuva cai?','guarda-chuva',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_266','usr_001','Minha voz é terna, minha cintura é esbelta.','violino',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_267','usr_001','Que instrumento pode fazer qualquer som e ser ouvido?','voz',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_268','usr_001','Meu trovão vem antes do relâmpago.','vulcão',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_269','usr_001','Somos cinco pequenos objetos do dia a dia.','vogais',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_270','usr_001','Corro ao redor da cidade, mas nunca me movo.','muro',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_271','usr_001','Macia como seda, branca como leite, amarga como fel.','noz',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_272','usr_001','Uma colheita semeada e colhida no mesmo dia.','guerra',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_273','usr_001','Tenho três vidas.','água',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_274','usr_001','Brilhante como diamantes, barulhenta como trovão.','cachoeira',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_275','usr_001','A lua é meu pai. O mar é minha mãe.','onda',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_276','usr_001','Redondo como uma maçã. Fundo como uma xícara.','poço',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_277','usr_001','Ando em círculos, mas sempre em frente.','roda',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_278','usr_001','Uma cobra de couro, com uma mordida ardente.','chicote',NULL,'objetos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_279','usr_001','Sem voz chora, sem asas bate.','vento',NULL,'natureza',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_280','usr_001','Tenho quatro asas, mas não posso voar.','moinho de vento',NULL,'objetos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_281','usr_001','Existe uma invenção antiga.','janela',NULL,'objetos',1,50,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_282','usr_001','Quando jovem, sou doce ao sol.','vinho',NULL,'alimentos',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_283','usr_001','Sou o coração que não bate.','madeira',NULL,'natureza',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_284','usr_001','O que você deve dar antes de poder guardar?','palavra',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_285','usr_001','O que nenhum homem quer, mas nenhum homem quer perder?','trabalho',NULL,'abstrato',2,100,0,0,FALSE,TRUE,NULL,NULL,NULL),
('rdl_pt_286','usr_001','O que deve estar no forno, mas não pode ser assado?','fermento',NULL,'alimentos',3,150,0,0,FALSE,TRUE,NULL,NULL,NULL);
